export const item = [
    { id: 1, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 2, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 3, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 4, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 5, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 6, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 7, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 8, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true }
];
