// Добавить кураторов

export const item = [
    { id: 1, 
    profilePic: 'Manul.jpg',
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    } 
},

    { id: 2, 
    date: '11.02.2019',
    profilePic: 'Pic3.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 3, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 4, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 5, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    } 
},

    { id: 6, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 7, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 8, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 9, 
    date: '11.02.2019', 
    profilePic: 'osminozhek.png',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 10, 
    date: '11.02.2019', 
    profilePic: 'Pic3.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
 },
    
    { id: 11, 
    date: '11.02.2019',
    profilePic: 'Manul.jpg', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 12, 
    date: '11.02.2019',
    profilePic: 'noavatar.png', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 13, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 14, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 15, 
    date: '11.02.2019', 
    profilePic: 'Pic3.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 16, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 17, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 18, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 19, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 20, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
 },
    
    { id: 21, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 22, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 23, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 24, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
 },

    { id: 25, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 26, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 27, 
    date: '11.02.2019', 
    profilePic: 'Pic3.jpg',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 28, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 29, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 30, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 31, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 32, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 33, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    } },

    { id: 333, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 34, 
    date: '11.02.2019',
    profilePic: 'Manul.jpg', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 35, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
 },
    
    { id: 36, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 37, 
    date: '11.02.2019',
    profilePic: 'noavatar.png', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 38, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 39, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 40, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 41, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 42, 
    date: '11.02.2019', 
    profilePic: 'Pic3.jpg',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 43, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 44, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 45, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 46, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 47, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 48, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 49, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 50, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 51, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 52, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 53, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 54, 
    date: '11.02.2019', 
    profilePic: 'Pic3.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 55, 
    date: '11.02.2019', 
    profilePic: 'Pic3.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 56, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 57, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 58, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 59, 
    date: '11.02.2019', 
    profilePic: 'Pic3.jpg',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 60, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 61, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 62, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 63, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 64, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 65, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 66, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 67, 
    date: '11.02.2019',
    profilePic: 'noavatar.png',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    },
},
    
    { id: 68, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 69, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 70, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 71, 
    date: '11.02.2019', 
    profilePic: 'Pic3.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 72, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 73, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 74, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 75, 
    date: '11.02.2019',
    profilePic: 'noavatar.png', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
 },
    
    { id: 76, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 77, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
 },

    { id: 78, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 79, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 80, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 81, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 82, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 83, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},
    
    { id: 84, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
 },

    { id: 85, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '',
        educability_comment: '',
        quality: '',
        quality_comment: '',
        responsibility: '',
        responsibility_comment: '',
        initiative: '',
        initiative_comment: '',
        conflict: '',
        conflict_comment: '',
        relationship: '',
        relationship_comment: '',
        interest: '',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 86, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Савищенко', 
    FirstName: 'Сергей', 
    Patronymic: 'Евгеньевич', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false,
    comment: 'быстро и качественно выполняет задания',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: 5,
        educability_comment: 'хорошо',
        quality: 5,
        quality_comment: 'хорошо',
        responsibility: 5,
        responsibility_comment: 'хорошо',
        initiative: 5,
        initiative_comment: 'хорошо',
        conflict: 5,
        conflict_comment: 'хорошо',
        relationship: 5,
        relationship_comment: 'хорошо',
        interest: 5,
        interest_comment: 'хорошо',
        average_mark: '',
        date: null
    }
},

    { id: 87, 
    date: '11.02.2019', 
    profilePic: 'noavatar.png',
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: 'за время практики проявил себя хорошо',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '5',
        educability_comment: '',
        quality: '5',
        quality_comment: '',
        responsibility: '4',
        responsibility_comment: '',
        initiative: '5',
        initiative_comment: '',
        conflict: '4',
        conflict_comment: '',
        relationship: '4',
        relationship_comment: '',
        interest: '3',
        interest_comment: 'больше стараться',
        average_mark: '',
        date: null
    }
},

    { id: 88, 
    date: '11.02.2019', 
    profilePic: 'Miku.jpg',
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: 'за время практики проявил себя хорошо',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '4',
        educability_comment: '',
        quality: '3',
        quality_comment: '',
        responsibility: '5',
        responsibility_comment: '',
        initiative: '4',
        initiative_comment: '',
        conflict: '4',
        conflict_comment: '',
        relationship: '4',
        relationship_comment: '',
        interest: '5',
        interest_comment: '',
        average_mark: '',
        date: ''
    }
},

    { id: 89, 
    date: '11.02.2019', 
    profilePic: 'Manul.jpg',
    SecondName: 'Архипов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true,
    comment: '',
    starRatings: 0,
    Curator: '',
    ratingTable: {
        educability: '5',
        educability_comment: "замечаний нет",
        quality: "4",
        quality_comment: 'низкая скорость выполнения задач',
        responsibility: '5',
        responsibility_comment: 'замечаний нет',
        initiative: '5',
        initiative_comment: 'предлагает различные способы решения проблемы',
        conflict: '5',
        conflict_comment: 'не конфликтный',
        relationship: '4',
        relationship_comment: 'замечаний нет',
        interest: '5',
        interest_comment: 'полностью участвет в жизни проекта',
        average_mark: '',
        date: ''
    }
},   
];
