// Добавить кураторов
export const item = [
    { id: 1, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 2, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 3, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 4, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 5, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 6, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 7, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 8, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 9, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 10, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 11, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 12, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 13, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 14, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 15, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 16, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 17, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 18, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 19, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 20, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 21, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 22, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 23, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 24, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 25, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 26, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 27, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 28, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 29, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 30, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 31, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 32, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },
    
    { id: 33, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 333, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 34, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 35, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 36, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 37, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 38, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 39, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 40, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 41, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 42, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 43, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 44, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 45, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 46, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 47, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 48, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 49, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 50, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 51, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 52, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 53, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 54, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 55, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 56, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 57, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 58, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 59, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 60, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 61, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 62, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 63, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 64, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 65, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 66, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 67, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 68, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 69, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 70, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 71, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 72, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 73, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 74, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 75, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 76, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 77, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 78, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 79, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 80, 
    date: '11.02.2019', 
    SecondName: 'Иванов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 81, 
    date: '11.02.2019', 
    SecondName: 'Чижов', 
    FirstName: 'Владимир', 
    Patronymic: 'Иванович', 
    College: 'Политех', 
    Faculty: 'Программирование', 
    Speciality: 'Тестировщик',  
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com', 
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 82, 
    date: '11.02.2019', 
    SecondName: 'Скворцов', 
    FirstName: 'Николай', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ФАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: true, 
    rejected: false,
    onPractice: false,
    inArchive: false },

    { id: 83, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: true, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: false },
    
    { id: 84, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 85, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: true,
    onPractice: false,
    inArchive: false },

    { id: 86, 
    date: '11.02.2019', 
    SecondName: 'Савищенко', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    Curator: 'Андреев А.',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: true,
    inArchive: false },

    { id: 87, 
    date: '11.02.2019', 
    SecondName: 'Михайлов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 88, 
    date: '11.02.2019', 
    SecondName: 'Сидоров', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },

    { id: 89, 
    date: '11.02.2019', 
    SecondName: 'Архипов', 
    FirstName: 'Иван', 
    Patronymic: 'Иванович', 
    College: 'КГУ', 
    Faculty: 'ИАСТ', 
    Speciality: 'Разработчик', 
    PractiesBegining: '12.04.2019', 
    PractiesEnding: '12.09.2019', 
    Phone: '8 (999) 245-45-65', 
    Email: 'ivanov@mail.com',
    request: false, 
    approved: false, 
    rejected: false,
    onPractice: false,
    inArchive: true },   
];
